### ISSUE TITLE
No costume change occur

### ISSUE THREAD

**Issue by newbiepr** [ShinyColorsDB/ShinyColorsDB-EventViewer#11]
original game screenshot
https://i.imgur.com/C7bgVsw.png

this eventViewer screenshot
https://i.imgur.com/gr0iMKQ.png

game_event_communications , 400103602.

**Comment by alex94539** [comment]
too lazy to code today, eta next week

**Comment by alex94539** [comment]
@Cpk0521 help fix this issue :)))
