### ISSUE TITLE
spine data.json path is invalid

### ISSUE THREAD

**Issue by darwintree** [ShinyColorsDB/ShinyColorsDB-EventViewer#4]
https://event.shinycolors.moe/?eventId=400105508&eventType=game_event_communications

console error

`GET https://viewer.shinycolors.moe/spine/idols/undefined/1040250010/data.json 404`

**Comment by alex94539** [comment]
[5bfa90f](https://github.com/ShinyColorsDB/ShinyColorsDB-EventViewer/commit/5bfa90faefac3ead864c3e47d08f355487101c49)
fix missing attribute
