### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by thr3a** [ShinyColorsDB/ShinyColorsDB-EventViewer#40]
I am unable to view the stories due to a timeout error when fetching the JSON.
I have tried several URLs but encountered the same error. What should I do?

https://event.shinycolors.moe/?eventId=200901801
https://event.shinycolors.moe/?eventId=202100711

Also, is the JSON uploaded on GitHub or elsewhere?

Thank you.

**Comment by alex94539** [comment]
Computing center changed their firewall policy, banning all incoming traffics from outside of TW :(((
Migrated to GCP now, try clear your dns/browser cache and retry, should be fixed.

**Comment by thr3a** [comment]
It's working now! Thank you!
