### ISSUE TITLE
Uncaught Error: [object Object]addChildAt: The index 2 supplied is out of bounds 1

### ISSUE THREAD

**Issue by darwintree** [ShinyColorsDB/ShinyColorsDB-EventViewer#5]
Caused by https://event.shinycolors.moe/?eventId=400105508&eventType=game_event_communications

when played to 342

![image](https://user-images.githubusercontent.com/17946284/208301601-541b24f1-3411-4320-842e-8f578a903c09.png)

**Comment by alex94539** [comment]
Won't have time to fix this until new year's eve :((

**Comment by darwintree** [comment]
> Won't have time to fix this until new year's eve :((

Don't mind :)

**Comment by alex94539** [comment]
[ba7e3a](https://github.com/ShinyColorsDB/ShinyColorsDB-EventViewer/commit/ba7e3a9d1c22c07d04dbc80fec2cb87d14d53869)
Not tested but should fix this issue

**Comment by alex94539** [comment]
95df29 hotfix
