### ISSUE TITLE
Missing character

### ISSUE THREAD

**Issue by darwintree** [ShinyColorsDB/ShinyColorsDB-EventViewer#8]
https://event.shinycolors.moe/?eventType=produce_events&eventId=301500201

chiyuki should be in the scene

![image](https://user-images.githubusercontent.com/17946284/210390671-4f03e0f9-739b-41d9-af5d-366d6e91e969.png)

**Comment by alex94539** [comment]
[00849d6](https://github.com/ShinyColorsDB/ShinyColorsDB-EventViewer/commit/00849d64176170ff4dfdf0943c50a3615647d6ad)

fix wrong gsap version & fix direction bug
fix character bug
