### ISSUE TITLE
feat: use .json file from local disk

### ISSUE THREAD

**Issue by darwintree** [ShinyColorsDB/ShinyColorsDB-EventViewer#9]
Add a mode to load .json file from local disk, which can help to preview the translation or help DIY stories

**Comment by darwintree** [comment]
It would be better to allow json file injection. For example, if the EventViewer is running in a iframe, we can inject .json file from outside the iframe, which could improve Interoperability of current implementation

**Comment by alex94539** [comment]
using iframeMode
[link](https://event.shinycolors.moe/?iframeMode=1)
and `postMessage`
```
window.postMessage( {
    iframeJson: [ {}, {}, .... ]
})
```
to inject json
